name: Update Fork Manualy

on:
  workflow_dispatch:  # Tento trigger povoluje manuální spuštění
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Prune and checkout
        run: |
          git remote prune origin
          git checkout main
    
      - name: Configure git
        run: |
          git config --global user.name "ACPJanousek"
          git config --global user.email "petr.janousek@autocont.cz"
      
      - name: Fetch changes
        run: |
            git pull --unshallow
            git remote add upstream https://github.com/MicrosoftDocs/dynamics365smb-docs-pr.cs-cz.git || true
            git fetch upstream main
          
      - name: Merge changes
        run: |
            git checkout main
            git merge upstream/main || exit 0
            git push origin main
